import { sanityClient, urlFor } from 'lib/sanity'
import Head from 'next/head'
import Image from "next/image"
import Link from 'next/link'
import styles from 'styles/Home.module.css'

import { Swiper, SwiperSlide } from 'swiper/react';
import SwiperCore, { EffectFade, Scrollbar } from 'swiper/core';

SwiperCore.use([EffectFade, Scrollbar]);

const recipesQuery = `*[_type == "recipe"]|order(_createdAt desc){
                         _id, name, slug, mainImage
                      }`

export async function getStaticProps(){
  const recipes = await sanityClient.fetch(recipesQuery)
 
  return {
    props:{
      recipes
    }
  }
}


export default function Home({recipes}) {

  //console.log(recipes)

  return (
    <div style={{height:"auto"}} className={styles.container}>
      <Head>
        <title>All Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
        <h1 className={styles.title}>
          All recipes
        </h1>

      
        {recipes?.length == 0 &&  <h2>Nothing is here!</h2>}
      
        <ul>
        {recipes?.length >0 && recipes.map( recipe => 
          
          <li key={recipe._id}>
          
            <Link href={`/recipes/${recipe.slug.current}`}><a>

              <Image src={urlFor(recipe.mainImage).url()}
               width={300} height={200} 
               objectFit={'cover'} 
               loading="lazy" />

              <span>{recipe.name}</span>

            </a></Link>
          </li>

        )}
        </ul>


        {/* <div className="slider">
            <Swiper spaceBetween={20}
                    slidesPerView={4}
                    className="mySwiper"
                    scrollbar={{"hide": true}} >

            {recipes?.length >0 && recipes.map( recipe => 

                <SwiperSlide key={recipe._id}>
                  <div className="li" >
                  
                    <Link href={`/recipes/${recipe.slug.current}`}><a>

                      <Image src={urlFor(recipe.mainImage).url()}
                      width={300} height={200} 
                      objectFit={'cover'} 
                      loading="lazy" />

                      <span>{recipe.name}</span>

                    </a></Link>
                  </div>

                </SwiperSlide>
            )}             
                

            </Swiper>
        </div> */}


        <style jsx>{`

          .slider{
              position: relative;
              width: 100%;
              height: auto;
          }
          a {
              color: inherit;
              text-decoration: none;
              display: flex;
              flex-direction: column;
          }
          span{
            font-size: 1.5rem;
            font-weight: 700;
            text-transform: capitalize;
            margin-top: 1.2rem;
            color: #747474;
          }
          ul{
            padding:0;
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
            grid-gap: 1rem;
            width: 100%;
          }
          .li{
            padding: 1rem;
            border: 1px solid #c9c9c9;
            background: #e5e5e5;
            margin-bottom: 2rem;
          }
          li{
            list-style: none;
            padding: 1rem;
            border: 1px solid #c9c9c9;
            background: #e5e5e5;
          }
        `}</style>
        

    </div>
  )
}
